FROM python:3.13.5

WORKDIR /usr/src/app

COPY ./fastapi /usr/src/app

RUN pip install --no-cache-dir fastapi uvicorn[standard]

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]
